
build-frontend:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get remove cmdtest
    - apt-get install -y -qq nodejs yarn
  script:
    - pwd
    - ls
    - cd frontend && yarn
    - cd frontend && yarn build
  only:
    - dev
    - master

deploy-frontend:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get -qq install python python-pip ca-certificates
    - pip install awscli
  script:
    - aws s3 sync frontend/dist/ s3://chainlink.mitchmcaffee.com
  artifacts:
    paths:
      - frontend/dist
  only:
    - master
